export const ReactionMap = {
  UNDO: { text: "", rType: -1 },
  HAHA: { text: ":>", rType: 0 },
  NGAI: { text: "--b", rType: 1 },
  KHOC: { text: ":-((", rType: 2 },
  LIKE: { text: "/-strong", rType: 3 },
  DISLIKE: { text: "/-weak", rType: 4 },
  HEART: { text: "/-heart", rType: 5 },
  SMILE: { text: ":d", rType: 6 },
  CUOIRANUOCMAT: { text: ":')", rType: 7 },
  MISS: { text: ":-*", rType: 8 },
  HANHPHUC: { text: ":3", rType: 9 },
  SEELOVE: { text: ":b", rType: 10 },
  THING: { text: ";d", rType: 11 },
  SO: { text: ":~", rType: 12 },
  CUOIBITMIENG: { text: ";p", rType: 13 },
  CHUMO: { text: ":*", rType: 14 },
  LOLANG: { text: ";o", rType: 15 },
  RUNGNUOCMAT: { text: ":((", rType: 16 },
  CUOINHE: { text: ":)", rType: 17 },
  LELUOI: { text: ":p", rType: 18 },
  NGAINGUNG: { text: ":$", rType: 19 },
  GIAN: { text: ":-h", rType: 20 },
  CUOIGIAN: { text: "x-)", rType: 21 },
  COOLNGAU: { text: "8-)", rType: 22 },
  SUNGSUONG: { text: ";-d", rType: 23 },
  DOI: { text: ":q", rType: 24 },
  BUON: { text: ":(", rType: 25 },
  CUOIHIEM: { text: "b-)", rType: 26 },
  THACMAC: { text: ";?", rType: 27 },
  NGAI: { text: ":|", rType: 28 },
  BUADAU: { text: ";xx", rType: 29 },
  BUONSAU: { text: ":--|", rType: 30 },
  THEM: { text: ";g", rType: 31 },
  WOW: { text: ":o", rType: 32 },
  NGU: { text: ":z", rType: 33 },
  SƯỢNG: { text: ":l", rType: 34 },
  "NĂN NỈ": { text: "p-(", rType: 35 },
  BYE: { text: ":-bye", rType: 36 },
  MUTE: { text: ":x", rType: 37 },
  "KHÓ CHỊU": { text: "|-)", rType: 38 },
  "TOÁT MỒ HÔI": { text: ":wipe", rType: 39 },
  "HOẢNG HỐT": { text: ":!", rType: 40 },
  "LÀM NỦNG": { text: "8*", rType: 41 },
  CHỒ: { text: ":-dig", rType: 42 },
  ÓI: { text: ":t", rType: 43 },
  TRỐI: { text: "&-(", rType: 44 },
  "CƯỜI THAM": { text: ";-)", rType: 45 },
  VOTAY: { text: ":handclap", rType: 46 },
  KHINH: { text: ">-|", rType: 47 },
  "CHỐNG MẶT": { text: ":-f", rType: 48 },
  NGAIQUA: { text: ":-l", rType: 49 },
  BƠ: { text: ":-r", rType: 50 },
  "ĂN TÁN": { text: ";-/", rType: 51 },
  SUỴT: { text: ";-x", rType: 52 },
  NGÁP: { text: ":-o", rType: 53 },
  QUÁT: { text: ";-s", rType: 54 },
  CLOCK: { text: "🕑", rType: 55 },
  TIEUTAN: { text: ";!", rType: 56 },
  "CỔ VŨ": { text: ";f", rType: 57 },
  "DÂN CHƠI": { text: ":;", rType: 58 },
  "CƯỜI GƯỢNG": { text: ":v", rType: 59 },
  "HỐT HOẢNG": { text: ";-a", rType: 60 },
  LIẾC: { text: ":-<", rType: 61 },
  "TUYỆT VỜI": { text: ":))", rType: 62 },
  "THẤY TIỀN SÁNG MẮT": { text: "$-)", rType: 63 },
  // "CLOCK": { text: ":z", rType: 64 },
  "TAN VỠ": { text: "/-break", rType: 65 },
  SHIT: { text: "/-shit", rType: 66 },
  TIASET: { text: "/-li", rType: 67 },
  OK: { text: "/-ok", rType: 68 },
  HAI: { text: "/-v", rType: 69 },
  THANKS: { text: "/-thanks", rType: 70 },
  "NẮM ĐẤM": { text: "/-punch", rType: 71 },
  "BẮT TAY": { text: "/-share", rType: 111 },
  LẠY: { text: "_()_", rType: 73 },
  // "CLOCK": { text: "🕑", rType: 74 },
  NONE: { text: "", rType: 75 },
  // "CLOCK": { text: "🕑", rType: 76 },
  "XÒE TAY": { text: "👐", rType: 77 },
  // "CLOCK": { text: "🕑", rType: 78 },
  // "CLOCK": { text: "🕑", rType: 79 },
  DOG: { text: "🐶", rType: 80 },
  // "CLOCK": { text: "🕑", rType: 81 },
  "PIG": { text: "🐷", rType: 82 },
  // "CLOCK": { text: "🕑", rType: 83 },
  "CÂY THÔNG": { text: "🎄", rType: 84 },
  "GIỌT NƯỚC": { text: "💧", rType: 85 },
  "NGƯỜI TUYẾT": { text: "⛄", rType: 86 },
  "CẠN LY": { text: "🍻", rType: 87 },
  // "CLOCK": { text: "🕑", rType: 88 },
  "ĐÙI GÀ": { text: "🍗", rType: 89 },
  HOAHONG: { text: "/-rose", rType: 100 },
  FLAG: { text: "🇻🇳", rType: 201 },
  CUSTOM: { text: "Hà Huy Hoàng - Bot", rType: 200 },
};

export const Reactions = Object.keys(ReactionMap).reduce((acc, key) => {
  acc[key] = ReactionMap[key].text;
  return acc;
}, {});

export class Reaction {
  constructor(data, isGroup, appContext) {
    this.data = data;
    this.threadId = data.uidFrom == "0" ? data.idTo : data.uidFrom;
    this.isSelf = data.uidFrom == "0";
    this.isGroup = isGroup;
    if (data.idTo == "0") data.idTo = appContext.uid;
    if (data.uidFrom == "0") data.uidFrom = appContext.uid;
  }
}