export function dashboardHtml() {
  return `<!doctype html><html lang="vi"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
  <title>NGH Bot v2</title><style>
  :root{color-scheme:dark;font-family:Inter,system-ui,sans-serif;background:#06101f;color:#e6f1ff}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 80% 0,#12395d 0,transparent 35%),#06101f;min-height:100vh}.wrap{max-width:1180px;margin:auto;padding:36px 20px}header{display:flex;align-items:end;justify-content:space-between;gap:20px;margin-bottom:28px}h1{margin:0;font-size:clamp(28px,5vw,48px)}.accent{color:#67e8f9}.muted{color:#91a4ba}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(210px,1fr));gap:16px}.card{background:#0c1d31cc;border:1px solid #1e3a55;border-radius:20px;padding:20px;box-shadow:0 12px 35px #0005}.value{font-size:30px;font-weight:750;margin-top:9px}.bots{margin-top:22px}.bot{display:grid;grid-template-columns:50px 1fr auto;align-items:center;gap:14px;padding:15px 0;border-bottom:1px solid #17304a}.dot{width:12px;height:12px;border-radius:50%;background:#22c55e;box-shadow:0 0 15px #22c55e}.offline{background:#64748b;box-shadow:none}.badge{padding:6px 10px;border-radius:999px;background:#103353;color:#8eeaff;font-size:13px}@media(max-width:550px){header{align-items:start;flex-direction:column}.bot{grid-template-columns:24px 1fr}.bot .badge{grid-column:2}}
  </style></head><body><main class="wrap"><header><div><div class="accent">CONTROL CENTER</div><h1>NGH Bot <span class="accent">v2</span></h1><div class="muted">Giám sát nhẹ và an toàn cho hệ thống bot.</div></div><div id="updated" class="muted">Đang kết nối…</div></header>
  <section class="grid"><article class="card"><div class="muted">Bot online</div><div class="value" id="online">—</div></article><article class="card"><div class="muted">RAM tiến trình</div><div class="value" id="ram">—</div></article><article class="card"><div class="muted">Heap đang dùng</div><div class="value" id="heap">—</div></article><article class="card"><div class="muted">Scheduler</div><div class="value" id="jobs">—</div></article></section>
  <section class="card bots"><h2>Danh sách bot con</h2><div id="bots" class="muted">Đang tải…</div></section></main><script>
  const mb=n=>n==null?'—':(n/1048576).toFixed(1)+' MB';const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  async function refresh(){try{const [m,b]=await Promise.all([fetch('/api/metrics').then(r=>{if(!r.ok)throw Error(r.status);return r.json()}),fetch('/api/bots').then(r=>r.json())]);online.textContent=m.bots;ram.textContent=mb(m.memory.rss);heap.textContent=mb(m.memory.heapUsed);jobs.textContent=m.schedulerJobs;bots.innerHTML=b.length?b.map(x=>'<div class="bot"><i class="dot '+(x.status==='online'?'':'offline')+'"></i><div><strong>'+esc(x.name)+'</strong><div class="muted">Chủ: '+esc(x.ownerId)+'</div></div><span class="badge">'+esc(x.status)+' · '+(x.timeRemaining===-1?'Vô thời hạn':Math.max(0,Math.ceil(Number(x.timeRemaining||0)/86400000))+' ngày')+'</span></div>').join(''):'Chưa có bot con.';updated.textContent='Cập nhật '+new Date().toLocaleTimeString('vi-VN')}catch(e){updated.textContent='Mất kết nối';}}refresh();setInterval(refresh,10000);
  </script></body></html>`;
}
