import { Listener } from "./apis/listen.js";
import { getServerInfo, login } from "./apis/login.js";
import { logger } from "./utils.js";
import { createContext } from "./context.js";
import { getProfileMeFactory } from "./apis/getProfileMe.js";
import { sendReactionMessageFactory } from "./apis/sendReactionMessage.js";
import { inviteMemberMultiFactory } from "./apis/inviteMemberMulti.js";
import { changeGroupAvatarFactory } from "./apis/changeGroupAvatar.js";
import { changeAccountAvatarFactory } from "./apis/changeAccountAvatar.js";
import { changeGroupNameFactory } from "./apis/changeGroupName.js";
import { createGroupFactory } from "./apis/createGroup.js";
import { getUserByPhoneFactory } from "./apis/getUserByPhone.js";
import { getInfoMultiGroupFactory } from "./apis/getInfoMultiGroup.js";
import { getStickersByKeywordFactory } from "./apis/getStickersByKeyword.js";
import { getStickersDetailFactory } from "./apis/getStickersDetail.js";
import { removeMemberFactory } from "./apis/removeMember.js";
import { sendStickerFactory } from "./apis/sendSticker.js";
import { undoMessageFactory } from "./apis/undoMessage.js";
import { uploadAttachmentFactory } from "./apis/uploadAttachment.js";
import { sendMessageFactory } from "./apis/sendMessage.js";
import { deleteMessageFactory } from "./apis/deleteMessage.js";
import { getFriendProfileFactory } from "./apis/getFriendProfile.js";
import { sendVideoFactory } from "./apis/sendVideo.js";
import { getFriendsListFactory } from "./apis/getFriendsList.js";
import { getGroupListFactory } from "./apis/getGroupList.js";
import { changeGroupSettingFactory } from "./apis/changeGroupSetting.js";
import { blockUsersInGroupFactory } from "./apis/blockUsersInGroup.js";
import { addGroupAdminsFactory } from "./apis/addGroupAdmins.js";
import { removeGroupAdminsFactory } from "./apis/removeGroupAdmins.js";
import { getQRProfileUserFactory } from "./apis/getQRProfileUser.js";
import { sendBusinessCardFactory } from "./apis/sendBusinessCard.js";
import { sendFriendRequestFactory } from "./apis/sendFriendRequest.js";
import { getPendingMemberFactory } from "./apis/getPendingMember.js";
import { handleGroupPendingMembersFactory } from "./apis/handleGroupPendingMembers.js";
import { changeGroupOwnerFactory } from "./apis/changeGroupOwner.js";
import { leaveGroupFactory } from "./apis/leaveGroup.js";
import { sendCustomStickerFactory } from "./apis/sendCustomerSticker.js";
import { changeGroupLinkFactory } from "./apis/changeGroupLink.js";
import { sendToDoFactory } from "./apis/sendToDo.js";
import { getRecentMessageFactory } from "./apis/getRecentMessage.js";
import { parseLinkFactory } from "./apis/parseLink.js";
import { sendLinkFactory } from "./apis/sendLink.js";
import { sendVoiceFactory } from "./apis/sendVoice.js";
import { joinGroupByLinkFactory } from "./apis/joinGroupByLink.js";
import { getGroupInfoByLinkFactory } from "./apis/getGroupInfoByLink.js";
import { sendBankCardFactory } from "./apis/sendBankCard.js";
import { sendGifFactory } from "./apis/sendGif.js";
import { getMemberInGroupFactory } from "./apis/getMemberInGroup.js";
import { checkImageFactory } from "./apis/checkImageDirty.js";
import { sendImageFactory } from "./apis/sendImage.js";
import { sendFileFactory } from "./apis/sendFile.js";
import { uploadThumbnailFactory } from "./apis/uploadThumbnail.js";
import { sendMessageForwardFactory } from "./apis/sendMessageForward.js";
import { getBlockedMembersFactory } from "./apis/getBlockedMembers.js";
import { unblockMemberFactory } from "./apis/unblockMember.js";
import { getLinkGroupFromIDFactory } from "./apis/getLinkGroupFromID.js";
import { getAvatarUrlProfileFactory } from "./apis/getAvatarUrlProfile.js";
import { getStickerCategoryDetailFactory } from "./apis/getStickerCategoryDetail.js";
import { getPersonalizedStickerListFactory } from "./apis/getPersonalizedStickerList.js";
import { getStickerListKeyWordsFactory } from "./apis/getStickerListKeyWords.js";
import { searchStickerFactory } from "./apis/searchSticker.js";
import { joinGroupByIDFactory } from "./apis/joinGroupInvByID.js";
import { updatePersonalizedStickerListFactory } from "./apis/updatePersonalizedStickerList.js";
import { searchGifFactory } from "./apis/searchGif.js";
import { sendCallVoiceFactory } from "./apis/sendCallVoice.js";
import { getRecommendedFriendsFactory } from "./apis/getRecommendedFriends.js";
import { uploadThumbnailVideoFactory } from "./apis/uploadThumbnailVideo.js";
import { getGroupInvitationListFactory } from "./apis/getGroupInvitationList.js";
import { getInfoGroupFactory } from "./apis/getInfoGroup.js";
import { getTenorToStickerMapFactory } from "./apis/getTenorToStickerMap.js";
import { getUserByUsernameFactory } from "./apis/getUserByUsername.js";
import { removeFriendFactory } from "./apis/sendUnFriendRequest.js";
import { acceptFriendRequestFactory }  from "./apis/acceptFriendRequest.js";
import { undoFriendRequestFactory } from "./apis/undoFriendRequest.js";
import { disperseGroupFactory }  from "./apis/disperseGroup.js";
import { blockUserFactory } from "./apis/blockUser.js";
import { unblockUserFactory } from "./apis/unblockUser.js";
import { getMuteFactory } from "./apis/getMute.js";
import { setMuteFactory } from "./apis/setMute.js";
import { setPinnedConversationsFactory } from "./apis/setPinnedConversations.js";
import { updateProfileFactory } from "./apis/updateProfile.js";
import { updateSettingsFactory } from "./apis/updateSettings.js";
import { createPollFactory } from "./apis/createPoll.js";
import { sendReportFactory } from "./apis/sendReport.js";
import { upgradeGroupToCommunityFactory } from "./apis/upgradeGroupToCommunity.js";
import { pinGroupMsgFactory } from "./apis/pinGroupMsg.js";
import { addQuickMessageFactory } from "./apis/addQuickMessage.js";
import { addUnreadMarkFactory } from "./apis/addUnreadMark.js";
import { blockViewFeedFactory } from "./apis/blockViewFeed.js";
import { changeFriendAliasFactory } from "./apis/changeFriendAlias.js";
import { removeFriendAliasFactory } from "./apis/removeFriendAlias.js";
import { createAutoReplyFactory } from "./apis/createAutoReply.js";
import { deleteAutoReplyFactory } from "./apis/deleteAutoReply.js";
import { getAutoReplyListFactory } from "./apis/getAutoReplyList.js";
import { createReminderFactory } from "./apis/createReminder.js";
import { deleteChatFactory } from "./apis/deleteChat.js";
import { getAvatarListFactory } from "./apis/getAvatarList.js";
import { deleteAvatarFactory } from "./apis/deleteAvatar.js";
import { reuseAvatarFactory } from "./apis/reuseAvatar.js";
import { rejectFriendRequestFactory } from "./apis/rejectFriendRequest.js";
import { getFriendRequestListFactory } from "./apis/getFriendRequestedList.js";
import { joinGroupInviteBoxFactory } from "./apis/joinGroupInviteBox.js";
import { removeGroupInviteBoxFactory } from "./apis/removeGroupInviteBox.js";
import { getFriendBlockListFactory } from "./apis/getFriendBlockList.js";
import { disableGroupLinkFactory } from "./apis/disableGroupLink.js";

export let ANTI_DELETE_MESSAGE = false;
export let ANTI_DELETE_VOICE = false;
export let ANTI_DELETE_VIDEO = false;
export let ANTI_DELETE_STICKER = false;
export let ANTI_DELETE_ATTACHMENT = false;

class Zalo {
  constructor(credentials, options) {
    this.enableEncryptParam = true;
    this.validateParams(credentials);
    this.appContext = createContext(credentials, options, Zalo.API_TYPE, Zalo.API_VERSION);
    this.appContext.cookie = this.parseCookies(credentials.cookie);
  }

  parseCookies(cookie) {
    if (typeof cookie === "string") return cookie;
    if (cookie.cookies.length > 1) return JSON.stringify(cookie);
    const cookieString = cookie.cookies.map((c) => `${c.name}=${c.value}`).join("; ");
    return cookieString;
  }

  validateParams(credentials) {
    if (!credentials.imei || !credentials.cookie || !credentials.userAgent) {
      throw new Error("Missing required params");
    }
  }

  async login() {
    const loginData = await login(this);
    const serverInfo = await getServerInfo(this);
    if (!loginData || !serverInfo) throw new Error("Failed to login");
    this.appContext.secretKey = loginData.data.zpw_enk;
    this.appContext.uid = loginData.data.uid;
    this.appContext.idCloud = loginData.data.send2me_id;
    this.appContext.settings = serverInfo.setttings || serverInfo.settings;
    this.appContext.phoneNumber = loginData.data.phone_number;
    logger(this.appContext, true).info("Logged in as", loginData.data.uid);
    return new API(this.appContext, loginData.data);
  }
}

Zalo.API_TYPE = 30;
Zalo.API_VERSION = 667;

class API {
  constructor(appContext, loginInfo) {
    this.appContext = appContext;
    this.zpwServiceMap = loginInfo.zpw_service_map_v3;
    this.listener = new Listener(appContext, loginInfo.zpw_ws);
    this.getBotId = () => appContext.uid;
    this.getPhoneNumber = () => appContext.phoneNumber;
    this.getProfileMe = getProfileMeFactory(this, appContext);
    this.findUserByPhone = getUserByPhoneFactory(this, appContext);
    this.findUserByUsername = getUserByUsernameFactory(this, appContext);
    this.getFriendsRecommend = getRecommendedFriendsFactory(this, appContext);
    this.getStickersByKeyword = getStickersByKeywordFactory(this, appContext);
    this.getStickersDetail = getStickersDetailFactory(this, appContext);
    this.uploadAttachment = uploadAttachmentFactory(this, appContext);
    this.uploadThumbnail = uploadThumbnailFactory(this, appContext);
    this.uploadThumbnailVideo = uploadThumbnailVideoFactory(this, appContext);
    this.getGroupInfo = getInfoMultiGroupFactory(this, appContext);
    this.getInfoOneGroup = getInfoGroupFactory(this, appContext);
    this.createGroup = createGroupFactory(this, appContext);
    this.changeGroupAvatar = changeGroupAvatarFactory(this, appContext);
    this.changeAccountAvatar = changeAccountAvatarFactory(this, appContext);
    this.removeUserFromGroup = removeMemberFactory(this, appContext);
    this.addUserToGroup = inviteMemberMultiFactory(this, appContext);
    this.changeGroupName = changeGroupNameFactory(this, appContext);
    this.getUserInfo = getFriendProfileFactory(this, appContext);
    this.addReaction = sendReactionMessageFactory(this, appContext);
    this.sendSticker = sendStickerFactory(this, appContext);
    this.undoMessage = undoMessageFactory(this, appContext);
    this.sendMessage = sendMessageFactory(this, appContext);
    this.deleteMessage = deleteMessageFactory(this, appContext);
    this.sendVideo = sendVideoFactory(this, appContext);
    this.getAllFriends = getFriendsListFactory(this, appContext);
    this.getAllGroups = getGroupListFactory(this, appContext);
    this.changeGroupSetting = changeGroupSettingFactory(this, appContext);
    this.blockUsers = blockUsersInGroupFactory(this, appContext);
    this.addGroupAdmins = addGroupAdminsFactory(this, appContext);
    this.removeGroupAdmins = removeGroupAdminsFactory(this, appContext);
    this.getQRLink = getQRProfileUserFactory(this, appContext);
    this.sendBusinessCard = sendBusinessCardFactory(this, appContext);
    this.sendFriendRequest = sendFriendRequestFactory(this, appContext);
    this.getGroupPendingMembers = getPendingMemberFactory(this, appContext);
    this.handleGroupPendingMembers = handleGroupPendingMembersFactory(this, appContext);
    this.changeGroupOwner = changeGroupOwnerFactory(this, appContext);
    this.leaveGroup = leaveGroupFactory(this, appContext);
    this.sendCustomSticker = sendCustomStickerFactory(this, appContext);
    this.changeGroupLink = changeGroupLinkFactory(this, appContext);
    this.sendTodo = sendToDoFactory(this, appContext);
    this.getRecentMessages = getRecentMessageFactory(this, appContext);
    this.parseLink = parseLinkFactory(this, appContext);
    this.sendLink = sendLinkFactory(this, appContext);
    this.sendVoice = sendVoiceFactory(this, appContext);
    this.getGroupInfoByLink = getGroupInfoByLinkFactory(this, appContext);
    this.joinGroup = joinGroupByLinkFactory(this, appContext);
    this.sendBankCard = sendBankCardFactory(this, appContext);
    this.sendGif = sendGifFactory(this, appContext);
    this.getInfoMembers = getMemberInGroupFactory(this, appContext);
    this.checkImage = checkImageFactory();
    this.sendImage = sendImageFactory(this, appContext);
    this.sendFile = sendFileFactory(this, appContext);
    this.sendMessageForward = sendMessageForwardFactory(this, appContext);
    this.getGroupBlockList = getBlockedMembersFactory(this, appContext);
    this.unblockUsers = unblockMemberFactory(this, appContext);
    this.getLinkGroupByID = getLinkGroupFromIDFactory(this, appContext);
    this.getUserAvatar = getAvatarUrlProfileFactory(this, appContext);
    this.searchStickers = searchStickerFactory(this, appContext);
    this.getTenorToStickerMap = getTenorToStickerMapFactory(this, appContext);
    this.getStickersCategory = getStickerCategoryDetailFactory(this, appContext);
    this.getStickersPersonal = getPersonalizedStickerListFactory(this, appContext);
    this.getUpdateStickersPersonal = updatePersonalizedStickerListFactory(this, appContext);
    this.getStickerListKeyWords = getStickerListKeyWordsFactory(this, appContext);
    this.joinGroupByID = joinGroupByIDFactory(this, appContext);
    this.searchGif = searchGifFactory(this, appContext);
    this.callVoice = sendCallVoiceFactory(this, appContext);
    this.getGroupInvitationList = getGroupInvitationListFactory(this, appContext);
    this.removeFriend = removeFriendFactory(this, appContext);
    this.acceptFriendRequest = acceptFriendRequestFactory(this, appContext);
    this.undoFriendRequest = undoFriendRequestFactory(this, appContext);
    this.disperseGroup = disperseGroupFactory(this, appContext);
    this.blockUser = blockUserFactory(this, appContext);
    this.unblockUser = unblockUserFactory(this, appContext);
    this.getMute = getMuteFactory(this, appContext);
    this.setMute = setMuteFactory(this, appContext);
    this.setPinnedConversations = setPinnedConversationsFactory(this, appContext);
    this.updateProfile = updateProfileFactory(this, appContext);
    this.updateSettings = updateSettingsFactory(this, appContext);
    this.createPoll = createPollFactory(this, appContext);
    this.sendReport = sendReportFactory(this, appContext);
    this.upgradeGroupToCommunity = upgradeGroupToCommunityFactory(this, appContext);
    this.pinGroupMsg = pinGroupMsgFactory(this, appContext);
    this.addQuickMessage = addQuickMessageFactory(this, appContext);
    this.addUnreadMark = addUnreadMarkFactory(this, appContext);
    this.blockViewFeed = blockViewFeedFactory(this, appContext);
    this.changeFriendAlias = changeFriendAliasFactory(this, appContext);
    this.removeFriendAlias = removeFriendAliasFactory(this, appContext);
    this.createAutoReply = createAutoReplyFactory(this, appContext);
    this.deleteAutoReply = deleteAutoReplyFactory(this, appContext);
    this.getAutoReplyList = getAutoReplyListFactory(this, appContext);
    this.createReminder = createReminderFactory(this, appContext);
    this.deleteChat = deleteChatFactory(this, appContext);
    this.getAvatarList = getAvatarListFactory(this, appContext);
    this.deleteAvatar = deleteAvatarFactory(this, appContext);
    this.reuseAvatar = reuseAvatarFactory(this, appContext);
    this.rejectFriendRequest = rejectFriendRequestFactory(this, appContext);
    this.getFriendRequestList = getFriendRequestListFactory(this, appContext);
    this.joinGroupInviteBox = joinGroupInviteBoxFactory(this, appContext);
    this.removeGroupInviteBox = removeGroupInviteBoxFactory(this, appContext);
    this.getFriendBlockList = getFriendBlockListFactory(this, appContext);
    this.disableGroupLink = disableGroupLinkFactory(this, appContext);
  }
}

export { Zalo, API };
